name: Test
on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set env for production port
        run: echo "PRODUCTION_PORT=8080" >> $GITHUB_ENV

      - name: Build and serve Vue project
        run: |
          npm run build
          npm run start &
          sleep 10
          if ! curl -sS http://localhost:8080/ >/dev/null ; then
            echo "Error: Unable to serve the Vue project"
            exit 1
          fi
